import json
from pathlib import Path

aliases = {
    "hämoglobin": "hemoglobin",
    "hgb": "hemoglobin",
    "leukozyten": "wbc",
    "weiße blutkörperchen": "wbc",
    "thrombozyten": "platelets",
    "blutplättchen": "platelets",
    "erythrozyten": "rbc",
    "rote blutkörperchen": "rbc",
    "hämatokrit": "hematocrit",
    "neutrophile": "anc",
    "neutrophile granulozyten": "anc",
    "kreatinin": "creatinine",
    "gesamtbilirubin": "total_bilirubin",
    "bilirubin gesamt": "total_bilirubin",
    "direktes bilirubin": "direct_bilirubin",
    "albumin": "albumin",
    "gesamtprotein": "total_protein",
    "glukose": "glucose",
    "blutzucker": "glucose",
    "natrium": "sodium",
    "kalium": "potassium",
    "kalzium": "calcium",
    "calcium": "calcium",
    "kreatinkinase": "ck",
    "troponin t": "troponin_t",
    "troponin i": "troponin_i",
    "myoglobin": "myoglobin",
    "tsh": "tsh",
    "freies t3": "free_t3",
    "freies t4": "free_t4",
    "inr": "inr",
    "quick": "pt",
    "aptt": "aptt",
    "ptt": "aptt",
    "systolischer blutdruck": "systolic_bp",
    "diastolischer blutdruck": "diastolic_bp",
    "herzfrequenz": "pulse",
    "puls": "pulse",
    "körpertemperatur": "temperature",
    "körpergewicht": "weight",
    "größe": "height",
    "körpergröße": "height",
    "atemfrequenz": "respiratory_rate",
    "lymphozyten": "lymphocytes",
    "ldh": "ldh",
    "laktatdehydrogenase": "ldh",
    "ast": "ast",
    "got": "ast",
    "alt": "alt",
    "gpt": "alt",
    "alp": "alp",
    "alkalische phosphatase": "alp",
    "crp": "crp",
    "c-reaktives protein": "crp",
    "harnstoff": "bun",
    "bun": "bun",
    "neurofilament-leichtkette": "neurofilament_light",
}

path = Path(__file__).parent / "field_aliases.json"
with open(path, "w", encoding="utf-8") as f:
    json.dump(aliases, f, indent=2, ensure_ascii=False)
print("✓ field_aliases.json saved with correct UTF-8 encoding")